name: Generate Snake

on:
  schedule:
    - cron: "0 */12 * * *" 
  workflow_dispatch:

jobs:
  generate_snake:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Necessário para criar/escrever na branch 'output'
      id-token: write # Necessário para autenticação do deploy
      
    steps:
      - uses: actions/checkout@v3
        with:
          # Puxa o histórico completo (essencial para o Snake)
          ref: main 
          fetch-depth: 0 
          
      - uses: Platane/snk@v3
        id: snake-gif
        with:
          github_user_name: CarollineR
          outputs: dist/github-contribution-grid-snake.svg
        
      - uses: peaceiris/actions-gh-pages@v3 # Ação de deploy mais estável
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # O nome do branch que receberá os arquivos
          publish_branch: output
          # O diretório que contém o SVG gerado
          publish_dir: dist
