name: Generate Snake

on:
  schedule:
    # Roda a cada 12 horas (pode ajustar)
    - cron: "0 */12 * * *" 
  workflow_dispatch:

jobs:
  generate_snake:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Permite que a ação escreva no repositório (salve o SVG/GIF)
      id-token: write
      
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main # 
      - uses: Platane/snk@v3
        id: snake-gif
        with:
          github_user_name: CarollineR 
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
        
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: output
          publish_dir: dist
